name: CICD pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    print-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

              # Just print Hello, world
            - name: Print Hello
              run: echo "Hello, World!"
            
            # Open file and read the file
            - name: Open hello
              run: cat hello.txt
    
    
    Test:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone
              uses: actions/checkout@v2

            - name: install the node
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            - name: install packages
              run: npm install

            - name: Run the test
              run: npm run test


    Deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout the home directory
              run: |
                cd /home/ubuntu/cicd-ostad
                git pull
                pm2 status
                pm2 restart all

